### ISSUE TITLE
Doesn't work as expected with Nova TinyMCE

### ISSUE THREAD

**Issue by Anthony2511** [outl1ne/nova-page-manager#74]
Hello,

I tried to integrate the NovaTinyMCE package with the nova-page-manager.

When I integrate it normally, it does not work (the javascript of the package does not seem to be executed)

<img width="1180" alt="Capture d’écran 2021-03-31 à 16 47 48" src="https://user-images.githubusercontent.com/17065512/113163839-d55aec00-9240-11eb-9a26-5c8ade556e8c.png">

When I integrate NovaTinyMCE in the default fields (in vendors: vendor/optimistdigital/nova-page-manager/src/Nova/Page.php) it works.

<img width="1149" alt="Capture d’écran 2021-03-31 à 16 49 59" src="https://user-images.githubusercontent.com/17065512/113164144-236fef80-9241-11eb-955a-f25763daa964.png">

How is it possible ?

Thank you

**Comment by shahruslan** [comment]
I have the same problem

**Comment by shahruslan** [comment]
As I managed to find out, this is due to the fact that the textarea identifier contains the ">" symbol, for example, "data-> field_name". The ">" character is not allowed in the identifier, so the plugin cannot find a textarea element to convert to wysiwyg.
You need to change the scheme for creating the identifier.

**Comment by shahruslan** [comment]
I found how to fix this. The TinyMCE field has the ability to specify a custom identifier.
`NovaTinyMCE :: make ('text') -> id ('my-id')`
In this case, the field in the admin panel is displayed correctly.

**Comment by Anthony2511** [comment]
It's works Thanks !!
