### ISSUE TITLE
multilingual pages and parent/child relations

### ISSUE THREAD

**Issue by ni-grid** [outl1ne/nova-page-manager#89]
Hi,

I'm facing an issue with multilingual pages and parent/child relations. I'm using two languages: French and English.
Let's say I create a page with the slug `french-parent` and then its translation with the slug `english-parent`. 

Then I a create a `french-child` page whose parent is `french-parent` and an `english-child` page as a translation of `french-child`. `english-child`'s page path is `english-parent/english-child` and its `locale_parent_id` is the id of `french-child`.
So far so good. However the `parent_id` of this `english-child` page is `null`.

Is this normal? How can I access the parent page of a translated child page? 
Thanks

**Comment by Tarpsvo** [comment]
Hi!

Yeah, it's pretty confusing. The helper functions of the page manager handle this by default, but basically just one locale with a parent_id is used to create the child-parent structure of all pages.

If you call `nova_get_pages_structure()` you'll see that everything works as expected.

I know this is bad and I do have a plan to create a better localization system for the pages in the future (something similar to what menu builder has).

So, to answer your question: sadly, this is normal. In order to access the parent, you would have to take a huge detour:
First query all the locale-siblings, then check if any locale-siblings have a parent_id, then query that parent and finds its locale-siblings and check if any of the locale-siblings has the same locale as the page you're querying.

Easier way would be to use the helper methods and find your page there to be honest.

Good luck!
