### ISSUE TITLE
Can't change the page template afterwards

### ISSUE THREAD

**Issue by flymke** [outl1ne/nova-page-manager#95]
Hi there, maybe I am missing something but I can't change the page template on editing a page (actually I have 2 templates). When I newly create a page, I can choose the page template.

<img width="1235" alt="Bildschirmfoto 2021-09-15 um 14 32 10" src="https://user-images.githubusercontent.com/1081121/133433959-e8929353-c961-4605-87af-e9d3c9f557da.png">
<img width="1597" alt="Bildschirmfoto 2021-09-15 um 14 31 08" src="https://user-images.githubusercontent.com/1081121/133433966-581238e5-9920-481c-93d7-ad620213df85.png">

**Comment by Tarpsvo** [comment]
Hi! This is intentional - you can only set a template when creating a page to avoid any data loss. Otherwise you'd be looking at losing data or having data mismatches when switching between templates.

However, you can change the template in your database when you know what you're doing and really want to switch existing things around.
